# Generated by Django 5.2.5 on 2025-08-24 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_vien', models.CharField(max_length=20, unique=True, verbose_name='Mã số nhân viên')),
                ('anh_the', models.ImageField(blank=True, null=True, upload_to='anh_the/', verbose_name='Ảnh thẻ')),
                ('ho_ten', models.CharField(max_length=255, verbose_name='Họ và Tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('chieu_cao', models.FloatField(blank=True, null=True, verbose_name='Chiều cao (cm)')),
                ('can_nang', models.FloatField(blank=True, null=True, verbose_name='Cân nặng (kg)')),
                ('so_cccd', models.CharField(max_length=20, unique=True, verbose_name='Số CCCD/CMND')),
                ('ngay_cap_cccd', models.DateField(verbose_name='Ngày cấp CCCD')),
                ('noi_cap_cccd', models.CharField(max_length=255, verbose_name='Nơi cấp CCCD')),
                ('sdt_chinh', models.CharField(max_length=15, verbose_name='SĐT chính')),
                ('sdt_phu', models.CharField(blank=True, max_length=15, null=True, verbose_name='SĐT phụ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('dia_chi_thuong_tru', models.TextField(verbose_name='Địa chỉ Thường trú')),
                ('dia_chi_tam_tru', models.TextField(verbose_name='Địa chỉ Tạm trú')),
                ('trang_thai_hon_nhan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái Hôn nhân')),
                ('trinh_do_hoc_van', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trình độ Học vấn')),
                ('ten_lien_he_khan_cap', models.CharField(max_length=255, verbose_name='Tên người liên hệ khẩn cấp')),
                ('quan_he_khan_cap', models.CharField(max_length=50, verbose_name='Mối quan hệ')),
                ('sdt_khan_cap', models.CharField(max_length=15, verbose_name='SĐT người liên hệ khẩn cấp')),
                ('thong_tin_suc_khoe', models.TextField(blank=True, null=True, verbose_name='Ghi chú Sức khỏe')),
                ('thong_tin_ngan_hang', models.TextField(blank=True, null=True, verbose_name='Thông tin Ngân hàng')),
                ('trang_thai_lam_viec', models.CharField(choices=[('UV', 'Ứng viên'), ('TV', 'Thử việc'), ('CT', 'Chính thức'), ('TN', 'Tạm nghỉ'), ('DNV', 'Đã nghỉ việc')], default='UV', max_length=3, verbose_name='Trạng thái làm việc')),
                ('nguoi_gioi_thieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nhanvien', verbose_name='Người giới thiệu')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Danh sách Nhân viên',
            },
        ),
    ]
