# Generated by Django 5.2.5 on 2025-08-27 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhMaNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tien_to', models.CharField(default='NV', max_length=5, verbose_name='Tiền tố')),
                ('do_dai_so', models.PositiveIntegerField(default=4, verbose_name='Độ dài phần số')),
                ('so_hien_tai', models.PositiveIntegerField(default=0, verbose_name='Số hiện tại')),
            ],
            options={
                'verbose_name': 'Cấu hình Mã nhân viên',
                'verbose_name_plural': 'Cấu hình Mã nhân viên',
            },
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_ban', models.CharField(max_length=100, unique=True, verbose_name='Tên phòng ban')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Danh sách Phòng ban',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuc_vu', models.CharField(choices=[('NV', 'Nhân viên'), ('CT', 'Ca trưởng'), ('CHP', 'Chỉ huy phó'), ('CHT', 'Chỉ huy trưởng'), ('QLV', 'Quản lý Vùng'), ('TP', 'Trưởng phòng')], default='NV', max_length=3, verbose_name='Chức vụ')),
                ('ma_nhan_vien', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã số nhân viên')),
                ('anh_the', models.ImageField(blank=True, null=True, upload_to='anh_the/', verbose_name='Ảnh thẻ')),
                ('ho_ten', models.CharField(max_length=255, verbose_name='Họ và Tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('chieu_cao', models.FloatField(blank=True, null=True, verbose_name='Chiều cao (cm)')),
                ('can_nang', models.FloatField(blank=True, null=True, verbose_name='Cân nặng (kg)')),
                ('so_cccd', models.CharField(max_length=20, unique=True, verbose_name='Số CCCD/CMND')),
                ('ngay_cap_cccd', models.DateField(verbose_name='Ngày cấp CCCD')),
                ('noi_cap_cccd', models.CharField(max_length=255, verbose_name='Nơi cấp CCCD')),
                ('sdt_chinh', models.CharField(max_length=15, verbose_name='SĐT chính')),
                ('sdt_phu', models.CharField(blank=True, max_length=15, null=True, verbose_name='SĐT phụ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('dia_chi_thuong_tru', models.TextField(verbose_name='Địa chỉ Thường trú')),
                ('dia_chi_tam_tru', models.TextField(verbose_name='Địa chỉ Tạm trú')),
                ('trang_thai_hon_nhan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái Hôn nhân')),
                ('trinh_do_hoc_van', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trình độ Học vấn')),
                ('ten_lien_he_khan_cap', models.CharField(max_length=255, verbose_name='Tên người liên hệ khẩn cấp')),
                ('quan_he_khan_cap', models.CharField(max_length=50, verbose_name='Mối quan hệ')),
                ('sdt_khan_cap', models.CharField(max_length=15, verbose_name='SĐT người liên hệ khẩn cấp')),
                ('thong_tin_suc_khoe', models.TextField(blank=True, null=True, verbose_name='Ghi chú Sức khỏe')),
                ('thong_tin_ngan_hang', models.TextField(blank=True, null=True, verbose_name='Thông tin Ngân hàng')),
                ('trang_thai_lam_viec', models.CharField(choices=[('UV', 'Ứng viên'), ('TV', 'Thử việc'), ('CT', 'Chính thức'), ('TN', 'Tạm nghỉ'), ('DNV', 'Đã nghỉ việc')], default='UV', max_length=3, verbose_name='Trạng thái làm việc')),
                ('muc_tieu_lam_viec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.muctieu', verbose_name='Mục tiêu làm việc')),
                ('nguoi_gioi_thieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_duoc_gioi_thieu', to='users.nhanvien', verbose_name='Người giới thiệu')),
                ('quan_ly_truc_tiep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nhanvien', verbose_name='Quản lý trực tiếp')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản đăng nhập')),
                ('phong_ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.phongban', verbose_name='Phòng ban')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Danh sách Nhân viên',
            },
        ),
        migrations.CreateModel(
            name='LichSuCongTac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuc_vu', models.CharField(max_length=100, verbose_name='Chức vụ tại mục tiêu')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('mo_ta_nhiem_vu', models.TextField(blank=True, verbose_name='Mô tả nhiệm vụ')),
                ('muc_tieu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.muctieu', verbose_name='Mục tiêu')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_cong_tac', to='users.nhanvien')),
            ],
            options={
                'verbose_name': 'Lịch sử công tác',
                'verbose_name_plural': 'Lịch sử công tác',
                'ordering': ['-ngay_bat_dau'],
            },
        ),
        migrations.CreateModel(
            name='ChungChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chung_chi', models.CharField(max_length=255, verbose_name='Tên bằng cấp/chứng chỉ')),
                ('so_hieu', models.CharField(blank=True, max_length=100, verbose_name='Số hiệu')),
                ('ngay_cap', models.DateField(verbose_name='Ngày cấp')),
                ('ngay_het_han', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('file_scan', models.FileField(blank=True, null=True, upload_to='chung_chi/', verbose_name='File đính kèm')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chung_chi', to='users.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Bằng cấp/Chứng chỉ',
                'verbose_name_plural': 'Bằng cấp & Chứng chỉ',
            },
        ),
    ]
