# Generated by Django 5.2.5 on 2025-08-30 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CauHinhMaNhanVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tien_to",
                    models.CharField(
                        default="NV", max_length=5, verbose_name="Tiền tố"
                    ),
                ),
                (
                    "do_dai_so",
                    models.PositiveIntegerField(
                        default=4, verbose_name="Độ dài phần số"
                    ),
                ),
                (
                    "so_hien_tai",
                    models.PositiveIntegerField(default=0, verbose_name="Số hiện tại"),
                ),
            ],
            options={
                "verbose_name": "Cấu hình Mã nhân viên",
                "verbose_name_plural": "Cấu hình Mã nhân viên",
            },
        ),
        migrations.CreateModel(
            name="ChucDanh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_chuc_danh",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên chức danh"
                    ),
                ),
                (
                    "mo_ta",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "nhom_quyen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                        verbose_name="Nhóm quyền",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chức danh",
                "verbose_name_plural": "Danh sách Chức danh",
            },
        ),
        migrations.CreateModel(
            name="NhanVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_nhan_vien",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Mã số nhân viên",
                    ),
                ),
                (
                    "anh_the",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="anh_the/",
                        verbose_name="Ảnh thẻ",
                    ),
                ),
                ("ho_ten", models.CharField(max_length=255, verbose_name="Họ và Tên")),
                ("ngay_sinh", models.DateField(verbose_name="Ngày sinh")),
                (
                    "gioi_tinh",
                    models.CharField(
                        choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Khác")],
                        max_length=1,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "so_cccd",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Số CCCD/CMND"
                    ),
                ),
                (
                    "sdt_chinh",
                    models.CharField(max_length=15, verbose_name="SĐT chính"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "chuc_danh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.chucdanh",
                        verbose_name="Chức danh",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tài khoản đăng nhập",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhân viên",
                "verbose_name_plural": "Danh sách Nhân viên",
            },
        ),
        migrations.CreateModel(
            name="LichSuCongTac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ngay_bat_dau", models.DateField(verbose_name="Ngày bắt đầu")),
                (
                    "ngay_ket_thuc",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày kết thúc"
                    ),
                ),
                (
                    "la_vi_tri_hien_tai",
                    models.BooleanField(default=True, verbose_name="Vị trí hiện tại?"),
                ),
                (
                    "chuc_danh_kiem_nhiem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.chucdanh",
                        verbose_name="Chức danh tại mục tiêu",
                    ),
                ),
                (
                    "muc_tieu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.muctieu",
                        verbose_name="Mục tiêu",
                    ),
                ),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lich_su_cong_tac",
                        to="users.nhanvien",
                    ),
                ),
                (
                    "quan_ly_truc_tiep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.nhanvien",
                        verbose_name="Quản lý trực tiếp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử công tác",
                "verbose_name_plural": "Lịch sử công tác",
                "ordering": ["-ngay_bat_dau"],
            },
        ),
        migrations.CreateModel(
            name="PhongBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_phong_ban",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên phòng ban"
                    ),
                ),
                (
                    "mo_ta",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "nhom_quyen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                        verbose_name="Nhóm quyền chung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phòng ban",
                "verbose_name_plural": "Danh sách Phòng ban",
            },
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="phong_ban",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.phongban",
                verbose_name="Phòng ban",
            ),
        ),
    ]
