# Generated by Django 5.2.5 on 2025-09-02 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChungChi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_chung_chi",
                    models.CharField(
                        max_length=255, verbose_name="Tên chứng chỉ/Giấy phép"
                    ),
                ),
                (
                    "loai_chung_chi",
                    models.CharField(blank=True, max_length=100, verbose_name="Loại"),
                ),
                ("ngay_cap", models.DateField(verbose_name="Ngày cấp")),
                (
                    "ngay_het_han",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày hết hạn"
                    ),
                ),
                ("noi_cap", models.CharField(max_length=255, verbose_name="Nơi cấp")),
                (
                    "file_dinh_kem",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="chung_chi/",
                        verbose_name="File đính kèm",
                    ),
                ),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chung_chi",
                        to="users.nhanvien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chứng chỉ",
                "verbose_name_plural": "Danh sách Chứng chỉ",
                "ordering": ["-ngay_het_han"],
            },
        ),
    ]
