# Generated by Django 5.2.5 on 2025-09-02 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_chungchi"),
    ]

    operations = [
        migrations.AddField(
            model_name="nhanvien",
            name="chi_nhanh_ngan_hang",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Chi nhánh"
            ),
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="dia_chi_tam_tru",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Địa chỉ tạm trú"
            ),
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="dia_chi_thuong_tru",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Địa chỉ thường trú"
            ),
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="loai_hop_dong",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XDTH", "Xác định thời hạn"),
                    ("KXDTH", "Không xác định thời hạn"),
                    ("THOIVU", "Thời vụ"),
                ],
                max_length=10,
                verbose_name="Loại hợp đồng",
            ),
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="ngan_hang",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Tên ngân hàng"
            ),
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="ngay_vao_lam",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày vào làm"),
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="nguoi_lien_he_khan_cap",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Người liên hệ khẩn cấp"
            ),
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="sdt_khan_cap",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="SĐT khẩn cấp"
            ),
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="so_tai_khoan",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Số tài khoản ngân hàng"
            ),
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="trang_thai_lam_viec",
            field=models.CharField(
                choices=[
                    ("THUVIEC", "Thử việc"),
                    ("CHINHTHUC", "Chính thức"),
                    ("TAMHOAN", "Tạm hoãn"),
                    ("NGHIVIEC", "Đã nghỉ việc"),
                ],
                default="THUVIEC",
                max_length=10,
                verbose_name="Trạng thái làm việc",
            ),
        ),
        migrations.CreateModel(
            name="BangCapChungChi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_bang_cap",
                    models.CharField(
                        max_length=255, verbose_name="Tên bằng cấp/Chứng chỉ"
                    ),
                ),
                ("noi_cap", models.CharField(max_length=255, verbose_name="Nơi cấp")),
                ("ngay_cap", models.DateField(verbose_name="Ngày cấp")),
                (
                    "ngay_het_han",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày hết hạn"
                    ),
                ),
                (
                    "file_dinh_kem",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="bang_cap/",
                        verbose_name="File đính kèm",
                    ),
                ),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bang_cap",
                        to="users.nhanvien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bằng cấp & Chứng chỉ",
                "verbose_name_plural": "Danh sách Bằng cấp & Chứng chỉ",
            },
        ),
        migrations.CreateModel(
            name="HocVan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "truong_dao_tao",
                    models.CharField(
                        max_length=255, verbose_name="Trường/Trung tâm đào tạo"
                    ),
                ),
                (
                    "chuyen_nganh",
                    models.CharField(max_length=255, verbose_name="Chuyên ngành"),
                ),
                ("trinh_do", models.CharField(max_length=100, verbose_name="Trình độ")),
                ("tu_ngay", models.DateField(verbose_name="Từ ngày")),
                ("den_ngay", models.DateField(verbose_name="Đến ngày")),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hoc_van",
                        to="users.nhanvien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Học vấn",
                "verbose_name_plural": "Quá trình Học vấn",
            },
        ),
        migrations.DeleteModel(
            name="ChungChi",
        ),
    ]
