# Generated by Django 5.2.5 on 2025-09-15 16:02

import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_nhanvien_chi_nhanh_ngan_hang_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MauVanBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_mau",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tên mẫu"
                    ),
                ),
                (
                    "loai_van_ban",
                    models.CharField(
                        choices=[
                            ("HD", "Hợp đồng lao động"),
                            ("KT", "Quyết định khen thưởng"),
                            ("KL", "Quyết định kỷ luật"),
                        ],
                        max_length=2,
                        verbose_name="Loại văn bản",
                    ),
                ),
                ("noi_dung", tinymce.models.HTMLField(verbose_name="Nội dung mẫu")),
            ],
            options={
                "verbose_name": "Mẫu văn bản",
                "verbose_name_plural": "Quản lý Mẫu văn bản",
            },
        ),
        migrations.RemoveField(
            model_name="lichsucongtac",
            name="la_vi_tri_hien_tai",
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="email",
            field=models.EmailField(
                default="chua_co_email@example.com",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="sdt_chinh",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="SĐT chính"
            ),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nhan_vien",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tài khoản đăng nhập",
            ),
        ),
        migrations.CreateModel(
            name="HopDongLaoDong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_hop_dong",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số hợp đồng"
                    ),
                ),
                ("ngay_ky", models.DateField(verbose_name="Ngày ký")),
                ("ngay_hieu_luc", models.DateField(verbose_name="Ngày hiệu lực")),
                (
                    "ngay_het_han",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày hết hạn"
                    ),
                ),
                (
                    "luong_co_ban",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Lương cơ bản"
                    ),
                ),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hop_dong",
                        to="users.nhanvien",
                    ),
                ),
                (
                    "mau_hop_dong",
                    models.ForeignKey(
                        limit_choices_to={"loai_van_ban": "HD"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.mauvanban",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hợp đồng lao động",
                "verbose_name_plural": "Danh sách Hợp đồng",
                "ordering": ["-ngay_hieu_luc"],
            },
        ),
        migrations.CreateModel(
            name="QuyetDinh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_quyet_dinh",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số quyết định"
                    ),
                ),
                (
                    "loai_quyet_dinh",
                    models.CharField(
                        choices=[("KT", "Khen thưởng"), ("KL", "Kỷ luật")],
                        max_length=2,
                        verbose_name="Loại quyết định",
                    ),
                ),
                ("ngay_quyet_dinh", models.DateField(verbose_name="Ngày quyết định")),
                ("ly_do", models.TextField(verbose_name="Lý do")),
                (
                    "noi_dung_chi_tiet",
                    models.TextField(
                        blank=True, verbose_name="Nội dung chi tiết (nếu có)"
                    ),
                ),
                (
                    "mau_quyet_dinh",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.mauvanban",
                    ),
                ),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quyet_dinh",
                        to="users.nhanvien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quyết định",
                "verbose_name_plural": "Danh sách Quyết định",
                "ordering": ["-ngay_quyet_dinh"],
            },
        ),
    ]
