# Generated by Django 5.2.5 on 2025-09-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phancongcatruc",
            name="ngay_truc",
            field=models.DateField(db_index=True, verbose_name="Ngày trực"),
        ),
    ]
