# Generated by Django 5.2.5 on 2025-08-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_ban', models.CharField(max_length=100, unique=True, verbose_name='Tên phòng ban')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Danh mục Phòng ban',
            },
        ),
        migrations.CreateModel(
            name='ThongTinCongTy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cong_ty', models.CharField(default='Công ty TNHH Dịch vụ Bảo vệ XYZ', max_length=255, verbose_name='Tên công ty')),
                ('dia_chi', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo công ty')),
            ],
            options={
                'verbose_name': 'Thông tin Công ty',
                'verbose_name_plural': 'Thông tin Công ty',
            },
        ),
        migrations.CreateModel(
            name='ChucDanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuc_danh', models.CharField(max_length=100, unique=True, verbose_name='Tên chức danh')),
                ('phong_ban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phongban', verbose_name='Thuộc phòng ban')),
            ],
            options={
                'verbose_name': 'Chức danh',
                'verbose_name_plural': 'Danh mục Chức danh',
            },
        ),
    ]
