# Generated by Django 5.2.5 on 2025-08-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KhachHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_cong_ty",
                    models.CharField(max_length=255, verbose_name="Tên công ty"),
                ),
                (
                    "ma_so_thue",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Mã số thuế"
                    ),
                ),
                ("dia_chi", models.TextField(verbose_name="Địa chỉ")),
                (
                    "nguoi_lien_he",
                    models.CharField(max_length=100, verbose_name="Người liên hệ"),
                ),
                (
                    "sdt_lien_he",
                    models.CharField(max_length=15, verbose_name="SĐT liên hệ"),
                ),
                (
                    "email_lien_he",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email liên hệ"
                    ),
                ),
            ],
            options={
                "verbose_name": "Khách hàng",
                "verbose_name_plural": "Danh sách Khách hàng",
            },
        ),
        migrations.CreateModel(
            name="MucTieu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_muc_tieu",
                    models.CharField(max_length=255, verbose_name="Tên mục tiêu"),
                ),
                ("dia_chi", models.TextField(verbose_name="Địa chỉ mục tiêu")),
            ],
            options={
                "verbose_name": "Mục tiêu",
                "verbose_name_plural": "Danh sách Mục tiêu",
            },
        ),
        migrations.CreateModel(
            name="HopDong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_hop_dong",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số hợp đồng"
                    ),
                ),
                ("ngay_ky", models.DateField(verbose_name="Ngày ký")),
                ("ngay_hieu_luc", models.DateField(verbose_name="Ngày hiệu lực")),
                ("ngay_het_han", models.DateField(verbose_name="Ngày hết hạn")),
                (
                    "file_hop_dong",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="hop_dong/",
                        verbose_name="File đính kèm",
                    ),
                ),
                (
                    "khach_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.khachhang",
                        verbose_name="Khách hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hợp đồng",
                "verbose_name_plural": "Danh sách Hợp đồng",
            },
        ),
    ]
