# Generated by Django 5.2.5 on 2025-08-29 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muctieu',
            name='chi_huy_truong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muc_tieu_quan_ly', to='users.nhanvien', verbose_name='Chỉ huy trưởng'),
        ),
        migrations.AddField(
            model_name='muctieu',
            name='hop_dong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.hopdong', verbose_name='Hợp đồng'),
        ),
    ]
