# Generated by Django 5.2.5 on 2025-08-29 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopdong',
            name='don_gia',
        ),
        migrations.RemoveField(
            model_name='hopdong',
            name='loai_thanh_toan',
        ),
        migrations.RemoveField(
            model_name='hopdong',
            name='so_vi_tri',
        ),
        migrations.CreateModel(
            name='CoHoiKinhDoanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach_hang', models.CharField(max_length=255, verbose_name='Tên khách hàng tiềm năng')),
                ('nguoi_lien_he', models.CharField(max_length=100, verbose_name='Người liên hệ')),
                ('sdt_lien_he', models.CharField(max_length=15, verbose_name='SĐT')),
                ('email_lien_he', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('trang_thai', models.CharField(choices=[('MOI', 'Mới'), ('TIEPCAN', 'Đã tiếp cận'), ('KHAOSAT', 'Đã khảo sát'), ('BG1', 'Đã báo giá lần 1'), ('BG2', 'Đã báo giá lần 2'), ('GUIHD', 'Đã gửi hợp đồng'), ('THANHCONG', 'Thành công (Chờ ký HĐ)'), ('TRIENKHAI', 'Đã triển khai'), ('TUCHOI', 'Từ chối')], default='MOI', max_length=10, verbose_name='Trạng thái')),
                ('ly_do_tu_choi', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('diem_tiem_nang', models.IntegerField(default=0, verbose_name='Điểm tiềm năng')),
                ('nhan_vien_phu_trach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nhanvien', verbose_name='Nhân viên phụ trách')),
            ],
            options={
                'verbose_name': 'Cơ hội Kinh doanh',
                'verbose_name_plural': 'DS Cơ hội Kinh doanh',
            },
        ),
        migrations.CreateModel(
            name='DieuKhoanHopDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_vi_tri', models.CharField(max_length=100, verbose_name='Tên loại vị trí')),
                ('so_luong', models.PositiveIntegerField(verbose_name='Số lượng vị trí')),
                ('loai_thanh_toan', models.CharField(choices=[('GIO', 'Theo giờ'), ('VITRI', 'Theo vị trí / tháng'), ('TRONGOI', 'Trọn gói')], max_length=10, verbose_name='Loại hình thanh toán')),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá (VNĐ)')),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dieu_khoan', to='clients.hopdong', verbose_name='Hợp đồng')),
            ],
            options={
                'verbose_name': 'Điều khoản Hợp đồng',
                'verbose_name_plural': 'Các Điều khoản Hợp đồng',
            },
        ),
        migrations.CreateModel(
            name='LichSuTuongTac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tuong_tac', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(verbose_name='Ghi chú')),
                ('co_hoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_tuong_tac', to='clients.cohoikinhdoanh')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nhanvien')),
            ],
            options={
                'ordering': ['-ngay_tuong_tac'],
            },
        ),
    ]
