# Generated by Django 5.2.5 on 2025-08-31 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KhachHangTiemNang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_cong_ty",
                    models.CharField(max_length=255, verbose_name="Tên công ty"),
                ),
                (
                    "nguoi_lien_he",
                    models.CharField(max_length=255, verbose_name="Người liên hệ"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("sdt", models.CharField(max_length=20, verbose_name="Số điện thoại")),
                ("dia_chi", models.TextField(verbose_name="Địa chỉ")),
                (
                    "nguon",
                    models.CharField(blank=True, max_length=100, verbose_name="Nguồn"),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
            ],
            options={
                "verbose_name": "Khách hàng Tiềm năng",
                "verbose_name_plural": "DS Khách hàng Tiềm năng",
            },
        ),
        migrations.RemoveField(
            model_name="hopdong",
            name="khach_hang",
        ),
        migrations.AlterModelOptions(
            name="muctieu",
            options={
                "verbose_name": "Mục tiêu Bảo vệ",
                "verbose_name_plural": "Danh sách Mục tiêu",
            },
        ),
        migrations.RemoveField(
            model_name="muctieu",
            name="chi_huy_truong",
        ),
        migrations.AddField(
            model_name="hopdong",
            name="gia_tri",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Giá trị Hợp đồng (VND)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="muctieu",
            name="nguoi_lien_he",
            field=models.CharField(
                default=0, max_length=255, verbose_name="Người liên hệ tại Mục tiêu"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="muctieu",
            name="quan_ly_muc_tieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="muc_tieu_quan_ly",
                to="users.nhanvien",
                verbose_name="Chỉ huy trưởng/Quản lý",
            ),
        ),
        migrations.AddField(
            model_name="muctieu",
            name="sdt_lien_he",
            field=models.CharField(
                default=0, max_length=20, verbose_name="SĐT liên hệ"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hopdong",
            name="so_hop_dong",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Số hợp đồng"
            ),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="dia_chi",
            field=models.TextField(verbose_name="Địa chỉ Mục tiêu"),
        ),
        migrations.AlterField(
            model_name="muctieu",
            name="hop_dong",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="muc_tieu",
                to="clients.hopdong",
                verbose_name="Hợp đồng",
            ),
        ),
        migrations.CreateModel(
            name="CoHoiKinhDoanh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_co_hoi",
                    models.CharField(max_length=255, verbose_name="Tên cơ hội"),
                ),
                (
                    "gia_tri_uoc_tinh",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Giá trị ước tính (VND)",
                    ),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_ket_thuc_du_kien",
                    models.DateField(verbose_name="Ngày kết thúc dự kiến"),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("MOI", "Mới"),
                            ("LIENHE", "Đã liên hệ"),
                            ("BAOGIA", "Đã gửi báo giá"),
                            ("THUONGLUONG", "Đang thương lượng"),
                            ("THANHCONG", "Thành công"),
                            ("THATBAI", "Thất bại"),
                        ],
                        default="MOI",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "nguoi_phu_trach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.nhanvien",
                        verbose_name="Người phụ trách",
                    ),
                ),
                (
                    "khach_hang_tiem_nang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.khachhangtiemnang",
                        verbose_name="Khách hàng tiềm năng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cơ hội Kinh doanh",
                "verbose_name_plural": "Pipeline Kinh doanh",
            },
        ),
        migrations.AddField(
            model_name="hopdong",
            name="co_hoi",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.cohoikinhdoanh",
                verbose_name="Cơ hội liên quan",
            ),
        ),
        migrations.DeleteModel(
            name="KhachHang",
        ),
    ]
