# Generated by Django 5.2.5 on 2025-08-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_hopdong_don_gia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichsutuongtac',
            name='co_hoi',
        ),
        migrations.RemoveField(
            model_name='dieukhoanhopdong',
            name='hop_dong',
        ),
        migrations.RemoveField(
            model_name='lichsutuongtac',
            name='nhan_vien',
        ),
        migrations.DeleteModel(
            name='CoHoiKinhDoanh',
        ),
        migrations.DeleteModel(
            name='DieuKhoanHopDong',
        ),
        migrations.DeleteModel(
            name='LichSuTuongTac',
        ),
    ]
