# Generated by Django 5.2.5 on 2025-08-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThongTinCongTy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_cong_ty",
                    models.CharField(
                        default="Công ty TNHH Dịch vụ Bảo vệ XYZ",
                        max_length=255,
                        verbose_name="Tên công ty",
                    ),
                ),
                (
                    "dia_chi",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Địa chỉ"
                    ),
                ),
                (
                    "so_dien_thoai",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Số điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos/",
                        verbose_name="Logo công ty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thông tin Công ty",
                "verbose_name_plural": "Thông tin Công ty",
            },
        ),
    ]
