# Generated by Django 5.2.5 on 2025-09-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_cong_ty",
                    models.CharField(max_length=255, verbose_name="Tên công ty"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos/", verbose_name="Logo"
                    ),
                ),
                (
                    "dia_chi",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Địa chỉ"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "sdt",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Số điện thoại"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
            ],
            options={
                "verbose_name": "Thông tin Công ty",
                "verbose_name_plural": "Thông tin Công ty",
            },
        ),
        migrations.DeleteModel(
            name="ThongTinCongTy",
        ),
    ]
