# Generated by Django 5.2.5 on 2025-08-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khoa_hoc', models.CharField(max_length=255, verbose_name='Tên khóa học')),
                ('mo_ta', models.TextField(verbose_name='Mô tả nội dung')),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Danh mục Khóa học',
            },
        ),
        migrations.CreateModel(
            name='PhieuThanhTra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_thanh_tra', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giờ thanh tra')),
                ('ket_luan', models.TextField(verbose_name='Kết luận')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='thanh_tra/', verbose_name='Hình ảnh bằng chứng')),
                ('muc_tieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.muctieu', verbose_name='Mục tiêu được thanh tra')),
                ('nhan_vien_bi_thanh_tra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_bi_thanh_tra', to='users.nhanvien', verbose_name='Nhân viên bị thanh tra')),
                ('nhan_vien_thanh_tra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_thanh_tra', to='users.nhanvien', verbose_name='Cán bộ thanh tra')),
            ],
            options={
                'verbose_name': 'Phiếu thanh tra',
                'verbose_name_plural': 'Danh sách Phiếu thanh tra',
            },
        ),
        migrations.CreateModel(
            name='DangKyHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dang_ky', models.DateField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('trang_thai', models.CharField(default='Đã đăng ký', max_length=50, verbose_name='Trạng thái')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nhanvien', verbose_name='Học viên')),
                ('khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.khoahoc', verbose_name='Khóa học')),
            ],
            options={
                'verbose_name': 'Đăng ký học',
                'verbose_name_plural': 'Danh sách Đăng ký học',
                'unique_together': {('khoa_hoc', 'nhan_vien')},
            },
        ),
    ]
