# Generated by Django 5.2.5 on 2025-08-30 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiemKiemTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_diem",
                    models.CharField(max_length=255, verbose_name="Tên điểm kiểm tra"),
                ),
                (
                    "vi_tri_mo_ta",
                    models.CharField(
                        help_text="Ví dụ: Cửa sau, góc tây nam nhà kho",
                        max_length=255,
                        verbose_name="Mô tả vị trí",
                    ),
                ),
                (
                    "qr_code_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Mã QR",
                    ),
                ),
                (
                    "thu_tu",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Thứ tự kiểm tra"
                    ),
                ),
            ],
            options={
                "verbose_name": "Điểm kiểm tra (Checkpoint)",
                "verbose_name_plural": "Danh sách Điểm kiểm tra",
                "ordering": ["thu_tu"],
            },
        ),
        migrations.CreateModel(
            name="LuotTuanTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thoi_gian_bat_dau",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian bắt đầu"
                    ),
                ),
                (
                    "thoi_gian_ket_thuc",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian kết thúc"
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "Đang tiến hành"),
                            ("COMPLETED", "Hoàn thành"),
                            ("INCOMPLETE", "Không hoàn thành"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "ghi_chu_chung",
                    models.TextField(blank=True, verbose_name="Ghi chú chung"),
                ),
            ],
            options={
                "verbose_name": "Lượt tuần tra",
                "verbose_name_plural": "Nhật ký Lượt tuần tra",
                "ordering": ["-thoi_gian_bat_dau"],
            },
        ),
        migrations.CreateModel(
            name="TuyenTuanTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_tuyen",
                    models.CharField(max_length=255, verbose_name="Tên tuyến tuần tra"),
                ),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
            ],
            options={
                "verbose_name": "Tuyến tuần tra",
                "verbose_name_plural": "Quản lý Tuyến tuần tra",
            },
        ),
        migrations.CreateModel(
            name="KetQuaKiemTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thoi_gian_quet",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian quét"
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("OK", "Bình thường"), ("ISSUE", "Có vấn đề")],
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "hinh_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="inspections/",
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "diem_kiem_tra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inspection.diemkiemtra",
                        verbose_name="Điểm kiểm tra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kết quả kiểm tra điểm",
                "verbose_name_plural": "Chi tiết Kết quả kiểm tra",
                "ordering": ["thoi_gian_quet"],
            },
        ),
    ]
