# Generated by Django 5.2.5 on 2025-08-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("inspection", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="luottuantra",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="users.nhanvien",
                verbose_name="Nhân viên thực hiện",
            ),
        ),
        migrations.AddField(
            model_name="ketquakiemtra",
            name="luot_tuan_tra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ket_qua",
                to="inspection.luottuantra",
                verbose_name="Lượt tuần tra",
            ),
        ),
        migrations.AddField(
            model_name="tuyentuantra",
            name="muc_tieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.muctieu",
                verbose_name="Mục tiêu",
            ),
        ),
        migrations.AddField(
            model_name="luottuantra",
            name="tuyen_tuan_tra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inspection.tuyentuantra",
                verbose_name="Tuyến tuần tra",
            ),
        ),
        migrations.AddField(
            model_name="diemkiemtra",
            name="tuyen_tuan_tra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diem_kiem_tra",
                to="inspection.tuyentuantra",
                verbose_name="Tuyến tuần tra",
            ),
        ),
    ]
