# Generated by Django 5.2.5 on 2025-09-05 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_khachhangtiemnang_remove_hopdong_khach_hang_and_more"),
        ("inspection", "0002_initial"),
        (
            "operations",
            "0004_alter_baocaodexuat_options_alter_baocaosuco_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DiemTuanTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_diem",
                    models.CharField(max_length=255, verbose_name="Tên điểm tuần tra"),
                ),
                (
                    "ma_qr",
                    models.CharField(max_length=255, unique=True, verbose_name="Mã QR"),
                ),
                (
                    "vi_tri_cu_the",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Vị trí cụ thể"
                    ),
                ),
                (
                    "thu_tu",
                    models.PositiveIntegerField(verbose_name="Thứ tự điểm quét"),
                ),
            ],
            options={
                "verbose_name": "Điểm Tuần Tra",
                "verbose_name_plural": "Các Điểm Tuần Tra",
                "ordering": ["loai_tuan_tra", "thu_tu"],
            },
        ),
        migrations.RemoveField(
            model_name="ketquakiemtra",
            name="diem_kiem_tra",
        ),
        migrations.RemoveField(
            model_name="ketquakiemtra",
            name="luot_tuan_tra",
        ),
        migrations.RemoveField(
            model_name="tuyentuantra",
            name="muc_tieu",
        ),
        migrations.RemoveField(
            model_name="luottuantra",
            name="tuyen_tuan_tra",
        ),
        migrations.AlterModelOptions(
            name="luottuantra",
            options={
                "ordering": ["-thoi_gian_bat_dau"],
                "verbose_name": "Lượt Tuần Tra",
                "verbose_name_plural": "Các Lượt Tuần Tra",
            },
        ),
        migrations.RemoveField(
            model_name="luottuantra",
            name="ghi_chu_chung",
        ),
        migrations.RemoveField(
            model_name="luottuantra",
            name="nhan_vien",
        ),
        migrations.AddField(
            model_name="luottuantra",
            name="ca_truc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.phancongcatruc",
            ),
        ),
        migrations.AlterField(
            model_name="luottuantra",
            name="thoi_gian_bat_dau",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="luottuantra",
            name="thoi_gian_ket_thuc",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="luottuantra",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "Đang tiến hành"),
                    ("COMPLETED", "Hoàn thành"),
                    ("INCOMPLETE", "Không hoàn thành"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="GhiNhanTuanTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thoi_gian_quet",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "hinh_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ghi_nhan_tuan_tra/",
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "diem_tuan_tra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inspection.diemtuantra",
                    ),
                ),
                (
                    "luot_tuan_tra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cac_ghi_nhan",
                        to="inspection.luottuantra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ghi Nhận Tuần Tra",
                "verbose_name_plural": "Các Ghi Nhận Tuần Tra",
                "ordering": ["thoi_gian_quet"],
            },
        ),
        migrations.CreateModel(
            name="LoaiTuanTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_loai",
                    models.CharField(max_length=255, verbose_name="Tên loại tuần tra"),
                ),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "muc_tieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cac_loai_tuan_tra",
                        to="clients.muctieu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loại Tuần Tra",
                "verbose_name_plural": "Các Loại Tuần Tra",
            },
        ),
        migrations.AddField(
            model_name="diemtuantra",
            name="loai_tuan_tra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_diem_tuan_tra",
                to="inspection.loaituantra",
            ),
        ),
        migrations.AddField(
            model_name="luottuantra",
            name="loai_tuan_tra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inspection.loaituantra",
            ),
        ),
        migrations.DeleteModel(
            name="DiemKiemTra",
        ),
        migrations.DeleteModel(
            name="KetQuaKiemTra",
        ),
        migrations.DeleteModel(
            name="TuyenTuanTra",
        ),
    ]
