# Generated by Django 5.2.5 on 2025-09-09 18:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_khachhangtiemnang_remove_hopdong_khach_hang_and_more"),
        ("inspection", "0003_diemtuantra_remove_ketquakiemtra_diem_kiem_tra_and_more"),
        ("users", "0003_nhanvien_chi_nhanh_ngan_hang_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HangMucKiemTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "noi_dung",
                    models.CharField(
                        max_length=255, verbose_name="Nội dung/Tiêu chí kiểm tra"
                    ),
                ),
                (
                    "nhom_kiem_tra",
                    models.CharField(
                        choices=[
                            ("NV_TAC_PHONG", "NV: Tác phong - Điều lệnh"),
                            ("NV_NGHIEP_VU", "NV: Kiến thức nghiệp vụ"),
                            ("MT_NHAN_SU", "Mục tiêu: Tình hình nhân sự"),
                            ("MT_CONG_CU", "Mục tiêu: Công cụ & Sổ sách"),
                            ("MT_AN_NINH", "Mục tiêu: Tình hình an ninh"),
                            ("KHAC", "Khác"),
                        ],
                        max_length=20,
                        verbose_name="Nhóm kiểm tra",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang áp dụng"),
                ),
            ],
            options={
                "verbose_name": "5. Hạng mục Thanh tra",
                "verbose_name_plural": "5. Các Hạng mục Thanh tra",
                "ordering": ["nhom_kiem_tra", "noi_dung"],
            },
        ),
        migrations.AlterModelOptions(
            name="diemtuantra",
            options={
                "ordering": ["loai_tuan_tra", "thu_tu"],
                "verbose_name": "2. Điểm Tuần Tra (Checkpoint)",
                "verbose_name_plural": "2. Các Điểm Tuần Tra (Checkpoints)",
            },
        ),
        migrations.AlterModelOptions(
            name="ghinhantuantra",
            options={
                "ordering": ["thoi_gian_quet"],
                "verbose_name": "4. Ghi Nhận Tuần Tra",
                "verbose_name_plural": "4. Các Ghi Nhận Tuần Tra",
            },
        ),
        migrations.AlterModelOptions(
            name="loaituantra",
            options={
                "verbose_name": "1. Loại Tuần Tra (NV Bảo vệ)",
                "verbose_name_plural": "1. Các Loại Tuần Tra (NV Bảo vệ)",
            },
        ),
        migrations.AlterModelOptions(
            name="luottuantra",
            options={
                "ordering": ["-thoi_gian_bat_dau"],
                "verbose_name": "3. Lượt Tuần Tra",
                "verbose_name_plural": "3. Các Lượt Tuần Tra",
            },
        ),
        migrations.CreateModel(
            name="BienBanThanhTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thoi_gian_kiem_tra",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Thời gian kiểm tra",
                    ),
                ),
                (
                    "loai_thanh_tra",
                    models.CharField(
                        choices=[
                            ("NV_DINH_KY", "Thanh tra Nhân viên (Định kỳ)"),
                            ("NV_DOT_XUAT", "Thanh tra Nhân viên (Đột xuất)"),
                            ("MT_DINH_KY", "Thanh tra Mục tiêu (Định kỳ)"),
                            ("MT_DOT_XUAT", "Thanh tra Mục tiêu (Đột xuất)"),
                        ],
                        max_length=20,
                        verbose_name="Loại hình",
                    ),
                ),
                (
                    "danh_gia_chung",
                    models.TextField(
                        blank=True, verbose_name="Đánh giá chung và Biện pháp khắc phục"
                    ),
                ),
                (
                    "muc_tieu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.muctieu",
                        verbose_name="Mục tiêu kiểm tra",
                    ),
                ),
                (
                    "nhan_vien_duoc_kiem_tra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cac_lan_bi_thanh_tra",
                        to="users.nhanvien",
                        verbose_name="Nhân viên được kiểm tra",
                    ),
                ),
                (
                    "thanh_tra_vien",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cac_cuoc_thanh_tra",
                        to="users.nhanvien",
                        verbose_name="Thanh tra viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "6. Biên bản Thanh tra",
                "verbose_name_plural": "6. Các Biên bản Thanh tra",
                "ordering": ["-thoi_gian_kiem_tra"],
            },
        ),
        migrations.CreateModel(
            name="BuoiHuanLuyen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_buoi_huan_luyen",
                    models.CharField(
                        max_length=255, verbose_name="Tên buổi huấn luyện/đào tạo"
                    ),
                ),
                ("noi_dung", models.TextField(verbose_name="Nội dung chính")),
                ("ngay_to_chuc", models.DateField(verbose_name="Ngày tổ chức")),
                (
                    "thoi_luong",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Thời lượng (ví dụ: 4 giờ)",
                    ),
                ),
                (
                    "giang_vien",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cac_buoi_giang_day",
                        to="users.nhanvien",
                        verbose_name="Giảng viên/Người hướng dẫn",
                    ),
                ),
                (
                    "nhan_vien_tham_gia",
                    models.ManyToManyField(
                        related_name="cac_buoi_dao_tao_da_hoc",
                        to="users.nhanvien",
                        verbose_name="Nhân viên tham gia",
                    ),
                ),
            ],
            options={
                "verbose_name": "8. Buổi Huấn luyện & Đào tạo",
                "verbose_name_plural": "8. Các Buổi Huấn luyện & Đào tạo",
                "ordering": ["-ngay_to_chuc"],
            },
        ),
        migrations.CreateModel(
            name="KetQuaKiemTra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ket_qua",
                    models.CharField(
                        choices=[
                            ("DAT", "Đạt"),
                            ("KHONG_DAT", "Không đạt"),
                            ("CAI_THIEN", "Cần cải thiện"),
                        ],
                        max_length=20,
                        verbose_name="Kết quả",
                    ),
                ),
                (
                    "ghi_chu",
                    models.TextField(blank=True, verbose_name="Ghi chú/Chi tiết"),
                ),
                (
                    "bien_ban",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ket_qua_chi_tiet",
                        to="inspection.bienbanthanhtra",
                    ),
                ),
                (
                    "hang_muc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inspection.hangmuckiemtra",
                        verbose_name="Hạng mục",
                    ),
                ),
            ],
            options={
                "verbose_name": "7. Kết quả Thanh tra Chi tiết",
                "verbose_name_plural": "7. Các Kết quả Thanh tra Chi tiết",
            },
        ),
    ]
