# Generated by Django 5.2.5 on 2025-09-10 02:00

from django.db import migrations

# Danh sách các hạng mục kiểm tra tiêu chuẩn
DEFAULT_INSPECTION_ITEMS = {
    # Nhóm thanh tra Nhân viên
    'NV_TAC_PHONG': [
        "Đầu tóc gọn gàng, đúng quy định",
        "Mặc đồng phục đúng, sạch sẽ, thẳng thớm",
        "Đeo bảng tên đúng vị trí",
        "Mang giày, vớ đúng quy định",
        "Tác phong nghiêm túc, thái độ lịch sự",
        "Không sử dụng điện thoại cá nhân khi làm nhiệm vụ",
    ],
    'NV_NGHIEP_VU': [
        "Nắm vững chức năng, nhiệm vụ tại vị trí",
        "Biết số điện thoại khẩn cấp (PCCC, Công an...)",
        "Biết vị trí đặt các trang thiết bị PCCC",
        "Biết cách sử dụng các công cụ hỗ trợ được trang bị",
    ],
    # Nhóm thanh tra Mục tiêu
    'MT_NHAN_SU': [
        "Quân số tại mục tiêu có đầy đủ theo phương án không?",
        "Nhân viên có mặt đúng vị trí được phân công không?",
        "Có nhân viên nào vắng mặt không lý do không?",
    ],
    'MT_CONG_CU': [
        "Sổ sách ghi chép có đầy đủ, sạch sẽ không?",
        "Công cụ hỗ trợ (bộ đàm, đèn pin...) có đủ và hoạt động tốt không?",
        "Biên bản bàn giao ca trực có được ghi chép đúng quy định không?",
    ],
    'MT_AN_NINH': [
        "Tình hình an ninh, trật tự trong ca trực có ổn định không?",
        "Hệ thống camera, báo động (nếu có) có hoạt động bình thường không?",
        "Các cửa ra vào, lối thoát hiểm có đảm bảo an toàn không?",
    ],
}

def populate_hang_muc_kiem_tra(apps, schema_editor):
    """
    Hàm này sẽ được gọi khi chạy migration, nó sẽ tạo các hạng mục mẫu.
    """
    HangMucKiemTra = apps.get_model('inspection', 'HangMucKiemTra')
    
    for group_code, items in DEFAULT_INSPECTION_ITEMS.items():
        for item_content in items:
            # get_or_create để tránh tạo trùng lặp nếu chạy lại migration
            HangMucKiemTra.objects.get_or_create(
                nhom_kiem_tra=group_code,
                noi_dung=item_content,
                defaults={'is_active': True}
            )

class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_diemtuantra_remove_ketquakiemtra_diem_kiem_tra_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_hang_muc_kiem_tra),
    ]
