# Generated by Django 5.2.5 on 2025-09-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0004_hangmuckiemtra_alter_diemtuantra_options_and_more"),
        ("inspection", "0004_populate_hang_muc_kiem_tra"),
    ]

    operations = []
