# Generated by Django 5.2.5 on 2025-08-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapPhatCaNhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_luong",
                    models.PositiveIntegerField(verbose_name="Số lượng cấp phát"),
                ),
                (
                    "ngay_cap_phat",
                    models.DateField(auto_now_add=True, verbose_name="Ngày cấp phát"),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
            ],
            options={
                "verbose_name": "Cấp phát Cá nhân",
                "verbose_name_plural": "Lịch sử Cấp phát Cá nhân",
            },
        ),
        migrations.CreateModel(
            name="CapPhatMucTieu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_luong",
                    models.PositiveIntegerField(verbose_name="Số lượng cấp phát"),
                ),
                (
                    "ngay_cap_phat",
                    models.DateField(auto_now_add=True, verbose_name="Ngày cấp phát"),
                ),
            ],
            options={
                "verbose_name": "Cấp phát Mục tiêu",
                "verbose_name_plural": "Lịch sử Cấp phát Mục tiêu",
            },
        ),
        migrations.CreateModel(
            name="TrangBiTieuChuan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_luong",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Số lượng tiêu chuẩn"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trang bị Tiêu chuẩn",
                "verbose_name_plural": "Danh sách Trang bị Tiêu chuẩn",
            },
        ),
        migrations.CreateModel(
            name="VatTu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_vat_tu",
                    models.CharField(max_length=255, verbose_name="Tên vật tư"),
                ),
                (
                    "don_vi_tinh",
                    models.CharField(max_length=50, verbose_name="Đơn vị tính"),
                ),
                (
                    "so_luong_ton_kho",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số lượng tồn kho"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vật tư",
                "verbose_name_plural": "Danh mục Vật tư",
            },
        ),
    ]
