# Generated by Django 5.2.5 on 2025-09-09 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0005_alter_capphatcanhan_options_alter_phieuxuat_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capphatcanhan",
            options={},
        ),
        migrations.RemoveField(
            model_name="capphatcanhan",
            name="ghi_chu",
        ),
        migrations.RemoveField(
            model_name="capphatcanhan",
            name="ngay_cap_phat",
        ),
        migrations.RemoveField(
            model_name="capphatcanhan",
            name="nguoi_cap_phat",
        ),
        migrations.RemoveField(
            model_name="capphatcanhan",
            name="nguoi_nhan",
        ),
        migrations.RemoveField(
            model_name="capphatcanhan",
            name="so_luong",
        ),
        migrations.RemoveField(
            model_name="capphatcanhan",
            name="vat_tu",
        ),
        migrations.RemoveField(
            model_name="phieuxuat",
            name="so_luong",
        ),
        migrations.RemoveField(
            model_name="phieuxuat",
            name="vat_tu",
        ),
        migrations.AddField(
            model_name="phieuxuat",
            name="ghi_chu",
            field=models.TextField(blank=True, verbose_name="Ghi chú"),
        ),
        migrations.AddField(
            model_name="phieuxuat",
            name="so_phieu",
            field=models.CharField(
                editable=False,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Số phiếu",
            ),
        ),
        migrations.AlterField(
            model_name="phieucapphat",
            name="ngay_cap_phat",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Ngày cấp phát"
            ),
        ),
        migrations.AlterField(
            model_name="phieuxuat",
            name="ngay_xuat",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Ngày xuất"
            ),
        ),
        migrations.CreateModel(
            name="ChiTietPhieuXuat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_luong", models.PositiveIntegerField(verbose_name="Số lượng")),
                (
                    "phieu_xuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chi_tiet",
                        to="inventory.phieuxuat",
                    ),
                ),
                (
                    "vat_tu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.vattu",
                        verbose_name="Vật tư",
                    ),
                ),
            ],
        ),
    ]
