# Generated by Django 5.2.5 on 2025-09-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaoCao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Truy cập Báo cáo",
                "verbose_name_plural": "Truy cập Báo cáo",
            },
        ),
    ]
