# Generated by Django 5.2.5 on 2025-08-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("operations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baocaodexuat",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Người gửi",
            ),
        ),
        migrations.AddField(
            model_name="baocaosuco",
            name="nguoi_chiu_trach_nhiem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.nhanvien",
                verbose_name="Người chịu trách nhiệm",
            ),
        ),
        migrations.AddField(
            model_name="phancongcatruc",
            name="ca_lam_viec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.calamviec",
                verbose_name="Ca làm việc",
            ),
        ),
        migrations.AddField(
            model_name="phancongcatruc",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Nhân viên",
            ),
        ),
        migrations.AddField(
            model_name="chamcong",
            name="ca_truc",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.phancongcatruc",
                verbose_name="Ca trực",
            ),
        ),
        migrations.AddField(
            model_name="baocaosuco",
            name="ca_truc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.phancongcatruc",
                verbose_name="Ca trực",
            ),
        ),
        migrations.AddField(
            model_name="vitrichot",
            name="muc_tieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vi_tri_chot",
                to="clients.muctieu",
                verbose_name="Mục tiêu",
            ),
        ),
        migrations.AddField(
            model_name="phancongcatruc",
            name="vi_tri_chot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.vitrichot",
                verbose_name="Vị trí chốt",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="phancongcatruc",
            unique_together={("vi_tri_chot", "nhan_vien", "ngay_truc", "ca_lam_viec")},
        ),
    ]
