# Generated by Django 5.2.5 on 2025-09-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_alter_phancongcatruc_ngay_truc"),
        ("users", "0003_nhanvien_chi_nhanh_ngan_hang_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baocaodexuat",
            options={
                "ordering": ["-ngay_gui"],
                "verbose_name": "Báo cáo & Đề xuất",
                "verbose_name_plural": "DS Báo cáo & Đề xuất",
            },
        ),
        migrations.AlterModelOptions(
            name="baocaosuco",
            options={
                "ordering": ["-thoi_gian_bao_cao"],
                "verbose_name": "Báo cáo Sự cố",
                "verbose_name_plural": "Danh sách Báo cáo Sự cố",
            },
        ),
        migrations.AlterModelOptions(
            name="calamviec",
            options={
                "ordering": ["gio_bat_dau"],
                "verbose_name": "Ca làm việc",
                "verbose_name_plural": "Danh sách Ca làm việc",
            },
        ),
        migrations.AddField(
            model_name="baocaosuco",
            name="nguoi_nhan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_bao_cao_su_co_da_nhan",
                to="users.nhanvien",
                verbose_name="Người nhận báo cáo",
            ),
        ),
        migrations.AlterField(
            model_name="baocaosuco",
            name="nguoi_chiu_trach_nhiem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cac_su_co_chiu_trach_nhiem",
                to="users.nhanvien",
                verbose_name="Người chịu trách nhiệm",
            ),
        ),
    ]
