# Generated by Django 5.2.5 on 2025-09-07 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_khachhangtiemnang_remove_hopdong_khach_hang_and_more"),
        ("inventory", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoaiVatTu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_loai",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên loại vật tư"
                    ),
                ),
            ],
            options={
                "verbose_name": "Loại vật tư",
                "verbose_name_plural": "Danh mục Loại vật tư",
            },
        ),
        migrations.CreateModel(
            name="NhaCungCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_nha_cung_cap",
                    models.CharField(max_length=255, verbose_name="Tên nhà cung cấp"),
                ),
                (
                    "dia_chi",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Địa chỉ"
                    ),
                ),
                (
                    "so_dien_thoai",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Số điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
            ],
            options={
                "verbose_name": "Nhà cung cấp",
                "verbose_name_plural": "Danh sách Nhà cung cấp",
            },
        ),
        migrations.RemoveField(
            model_name="capphatmuctieu",
            name="muc_tieu",
        ),
        migrations.RemoveField(
            model_name="capphatmuctieu",
            name="vat_tu",
        ),
        migrations.RemoveField(
            model_name="trangbitieuchuan",
            name="vat_tu",
        ),
        migrations.AlterModelOptions(
            name="vattu",
            options={
                "verbose_name": "Vật tư",
                "verbose_name_plural": "Danh sách Vật tư",
            },
        ),
        migrations.RemoveField(
            model_name="vattu",
            name="so_luong_ton_kho",
        ),
        migrations.AddField(
            model_name="vattu",
            name="dinh_muc_toi_thieu",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Định mức tồn tối thiểu"
            ),
        ),
        migrations.AddField(
            model_name="vattu",
            name="ghi_chu",
            field=models.TextField(blank=True, verbose_name="Ghi chú"),
        ),
        migrations.AddField(
            model_name="vattu",
            name="han_su_dung",
            field=models.DateField(blank=True, null=True, verbose_name="Hạn sử dụng"),
        ),
        migrations.AddField(
            model_name="vattu",
            name="hinh_anh",
            field=models.ImageField(
                blank=True, null=True, upload_to="vat_tu/", verbose_name="Hình ảnh"
            ),
        ),
        migrations.AddField(
            model_name="vattu",
            name="ma_vat_tu",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Mã vật tư",
            ),
        ),
        migrations.AddField(
            model_name="vattu",
            name="ngay_nhap",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày nhập cuối"
            ),
        ),
        migrations.AddField(
            model_name="vattu",
            name="so_luong_ton",
            field=models.PositiveIntegerField(default=0, verbose_name="Số lượng tồn"),
        ),
        migrations.AddField(
            model_name="vattu",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("SAN_SANG", "Sẵn sàng"),
                    ("YEU_CAU_NHAP", "Yêu cầu nhập"),
                    ("HET_HANG", "Hết hàng"),
                ],
                default="SAN_SANG",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AddField(
            model_name="vattu",
            name="vi_tri_luu_kho",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Vị trí lưu kho"
            ),
        ),
        migrations.AddField(
            model_name="vattu",
            name="loai",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.loaivattu",
                verbose_name="Loại vật tư",
            ),
        ),
        migrations.AddField(
            model_name="vattu",
            name="nha_cung_cap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.nhacungcap",
                verbose_name="Nhà cung cấp",
            ),
        ),
        migrations.CreateModel(
            name="PhieuNhap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_luong", models.PositiveIntegerField(verbose_name="Số lượng nhập")),
                (
                    "don_gia",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Đơn giá"
                    ),
                ),
                (
                    "ngay_nhap",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày nhập"),
                ),
                (
                    "nguoi_nhap",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người nhập",
                    ),
                ),
                (
                    "vat_tu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.vattu",
                        verbose_name="Vật tư",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu nhập kho",
                "verbose_name_plural": "Danh sách Phiếu nhập kho",
            },
        ),
        migrations.CreateModel(
            name="PhieuXuat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_luong", models.PositiveIntegerField(verbose_name="Số lượng xuất")),
                (
                    "ngay_xuat",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày xuất"),
                ),
                (
                    "muc_tieu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.muctieu",
                        verbose_name="Xuất cho mục tiêu",
                    ),
                ),
                (
                    "nguoi_xuat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phieu_xuat_nguoi_xuat",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xuất",
                    ),
                ),
                (
                    "vat_tu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.vattu",
                        verbose_name="Vật tư",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu xuất kho",
                "verbose_name_plural": "Danh sách Phiếu xuất kho",
            },
        ),
        migrations.DeleteModel(
            name="CapPhatCaNhan",
        ),
        migrations.DeleteModel(
            name="CapPhatMucTieu",
        ),
        migrations.DeleteModel(
            name="TrangBiTieuChuan",
        ),
    ]
