# Generated by Django 5.2.5 on 2025-08-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("inventory", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="capphatcanhan",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Nhân viên",
            ),
        ),
        migrations.AddField(
            model_name="capphatmuctieu",
            name="muc_tieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.muctieu",
                verbose_name="Mục tiêu",
            ),
        ),
        migrations.AddField(
            model_name="trangbitieuchuan",
            name="vat_tu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.vattu",
                verbose_name="Vật tư",
            ),
        ),
        migrations.AddField(
            model_name="capphatmuctieu",
            name="vat_tu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.vattu",
                verbose_name="Vật tư",
            ),
        ),
        migrations.AddField(
            model_name="capphatcanhan",
            name="vat_tu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.vattu",
                verbose_name="Vật tư",
            ),
        ),
    ]
