# Generated by Django 5.2.5 on 2025-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proposal",
            options={"verbose_name": "Đề xuất", "verbose_name_plural": "Các Đề xuất"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "verbose_name": "Công việc",
                "verbose_name_plural": "Các Công việc",
            },
        ),
        migrations.AlterField(
            model_name="proposal",
            name="tieu_de",
            field=models.CharField(max_length=255, verbose_name="Tiêu đề Đề xuất"),
        ),
        migrations.AlterField(
            model_name="task",
            name="tieu_de",
            field=models.CharField(max_length=255, verbose_name="Tiêu đề Công việc"),
        ),
    ]
