# Generated by Django 5.2.5 on 2025-09-07 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_loaivattu_nhacungcap_remove_capphatmuctieu_muc_tieu_and_more",
        ),
        ("users", "0003_nhanvien_chi_nhanh_ngan_hang_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapPhatCaNhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_luong",
                    models.PositiveIntegerField(verbose_name="Số lượng cấp phát"),
                ),
                (
                    "ngay_cap_phat",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày cấp phát"
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "nguoi_cap_phat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người cấp phát",
                    ),
                ),
                (
                    "nguoi_nhan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.nhanvien",
                        verbose_name="Nhân viên nhận",
                    ),
                ),
                (
                    "vat_tu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.vattu",
                        verbose_name="Vật tư cấp phát",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cấp phát cho Cá nhân",
                "verbose_name_plural": "DS Cấp phát cho Cá nhân",
            },
        ),
    ]
