# Generated by Django 5.2.5 on 2025-09-07 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_capphatcanhan"),
        ("users", "0003_nhanvien_chi_nhanh_ngan_hang_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capphatcanhan",
            options={
                "verbose_name": "Cấp phát cho Cá nhân (Cũ)",
                "verbose_name_plural": "DS Cấp phát cho Cá nhân (Cũ)",
            },
        ),
        migrations.AlterModelOptions(
            name="phieuxuat",
            options={
                "verbose_name": "Phiếu xuất kho (Mục tiêu)",
                "verbose_name_plural": "DS Phiếu xuất kho (Mục tiêu)",
            },
        ),
        migrations.CreateModel(
            name="PhieuCapPhat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_phieu",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Số phiếu",
                    ),
                ),
                (
                    "ngay_cap_phat",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày cấp phát"
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "nguoi_cap_phat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người cấp phát",
                    ),
                ),
                (
                    "nguoi_nhan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.nhanvien",
                        verbose_name="Nhân viên nhận",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu Cấp phát Cá nhân",
                "verbose_name_plural": "DS Phiếu Cấp phát Cá nhân",
            },
        ),
        migrations.CreateModel(
            name="ChiTietCapPhat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_luong", models.PositiveIntegerField(verbose_name="Số lượng")),
                (
                    "vat_tu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.vattu",
                        verbose_name="Vật tư",
                    ),
                ),
                (
                    "phieu_cap_phat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chi_tiet",
                        to="inventory.phieucapphat",
                    ),
                ),
            ],
        ),
    ]
