# Generated by Django 5.2.5 on 2025-08-30 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ca', models.CharField(max_length=100, verbose_name='Tên ca')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(verbose_name='Giờ kết thúc')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Danh sách Ca làm việc',
            },
        ),
        migrations.CreateModel(
            name='BaoCaoDeXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_bao_cao', models.CharField(choices=[('BC', 'Báo cáo'), ('DX', 'Đề xuất'), ('KN', 'Kiến nghị')], max_length=2, verbose_name='Loại')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung chi tiết')),
                ('ngay_gui', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('da_doc', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nhanvien', verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Báo cáo & Đề xuất',
                'verbose_name_plural': 'DS Báo cáo & Đề xuất',
            },
        ),
        migrations.CreateModel(
            name='PhanCongCaTruc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_truc', models.DateField(verbose_name='Ngày trực')),
                ('ca_lam_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.calamviec', verbose_name='Ca làm việc')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Phân công ca trực',
                'verbose_name_plural': 'Bảng Phân công ca trực',
                'ordering': ['ngay_truc', 'ca_lam_viec__gio_bat_dau'],
            },
        ),
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_check_in', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian Check-in')),
                ('thoi_gian_check_out', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian Check-out')),
                ('anh_check_in', models.ImageField(blank=True, null=True, upload_to='check_in/', verbose_name='Ảnh Check-in')),
                ('anh_check_out', models.ImageField(blank=True, null=True, upload_to='check_out/', verbose_name='Ảnh Check-out')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ca_truc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.phancongcatruc', verbose_name='Ca trực')),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Dữ liệu Chấm công',
            },
        ),
        migrations.CreateModel(
            name='BaoCaoSuCo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bao_cao', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian báo cáo')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung chi tiết')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='su_co/', verbose_name='Hình ảnh minh họa')),
                ('trang_thai', models.CharField(choices=[('MOI', 'Mới'), ('DAXEM', 'Đã xem'), ('DXL', 'Đang xử lý'), ('LEOTHANG', 'Đã leo thang'), ('DGQ', 'Đã giải quyết')], default='MOI', max_length=10, verbose_name='Trạng thái')),
                ('lich_su_xu_ly', models.TextField(blank=True, verbose_name='Lịch sử xử lý')),
                ('nguoi_chiu_trach_nhiem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nhanvien', verbose_name='Người chịu trách nhiệm')),
                ('ca_truc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.phancongcatruc', verbose_name='Ca trực')),
            ],
            options={
                'verbose_name': 'Báo cáo Sự cố',
                'verbose_name_plural': 'Danh sách Báo cáo Sự cố',
            },
        ),
        migrations.CreateModel(
            name='ViTriChot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_vi_tri', models.CharField(max_length=255, verbose_name='Tên vị trí')),
                ('muc_tieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vi_tri_chot', to='clients.muctieu', verbose_name='Mục tiêu')),
            ],
            options={
                'verbose_name': 'Vị trí chốt',
                'verbose_name_plural': 'Danh sách Vị trí chốt',
            },
        ),
        migrations.AddField(
            model_name='phancongcatruc',
            name='vi_tri_chot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.vitrichot', verbose_name='Vị trí chốt'),
        ),
        migrations.AlterUniqueTogether(
            name='phancongcatruc',
            unique_together={('vi_tri_chot', 'nhan_vien', 'ngay_truc', 'ca_lam_viec')},
        ),
    ]
