# Generated by Django 5.2.5 on 2025-08-24 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ca', models.CharField(max_length=100, verbose_name='Tên ca')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(verbose_name='Giờ kết thúc')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Danh sách Ca làm việc',
            },
        ),
        migrations.CreateModel(
            name='PhanCongCaTruc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_truc', models.DateField(verbose_name='Ngày trực')),
                ('ca_lam_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.calamviec', verbose_name='Ca làm việc')),
                ('muc_tieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.muctieu', verbose_name='Mục tiêu')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Phân công ca trực',
                'verbose_name_plural': 'Bảng Phân công ca trực',
                'unique_together': {('nhan_vien', 'ngay_truc')},
            },
        ),
    ]
