# Generated by Django 5.2.5 on 2025-08-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phancongcatruc',
            options={'ordering': ['ngay_truc', 'ca_lam_viec__gio_bat_dau'], 'verbose_name': 'Phân công ca trực', 'verbose_name_plural': 'Bảng Phân công ca trực'},
        ),
        migrations.CreateModel(
            name='BaoCaoDeXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_bao_cao', models.CharField(choices=[('BC', 'Báo cáo'), ('DX', 'Đề xuất'), ('KN', 'Kiến nghị')], max_length=2, verbose_name='Loại')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung chi tiết')),
                ('ngay_gui', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('da_doc', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nhanvien', verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Báo cáo & Đề xuất',
                'verbose_name_plural': 'DS Báo cáo & Đề xuất',
            },
        ),
    ]
