# Generated by Django 5.2.5 on 2025-08-24 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaoSuCo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bao_cao', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian báo cáo')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung chi tiết')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='su_co/', verbose_name='Hình ảnh minh họa')),
                ('ca_truc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.phancongcatruc', verbose_name='Ca trực')),
            ],
            options={
                'verbose_name': 'Báo cáo Sự cố',
                'verbose_name_plural': 'Danh sách Báo cáo Sự cố',
            },
        ),
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_check_in', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian Check-in')),
                ('thoi_gian_check_out', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian Check-out')),
                ('anh_check_in', models.ImageField(blank=True, null=True, upload_to='check_in/', verbose_name='Ảnh Check-in')),
                ('anh_check_out', models.ImageField(blank=True, null=True, upload_to='check_out/', verbose_name='Ảnh Check-out')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ca_truc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.phancongcatruc', verbose_name='Ca trực')),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Dữ liệu Chấm công',
            },
        ),
    ]
