# Generated by Django 5.2.5 on 2025-09-03 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0003_khachhangtiemnang_remove_hopdong_khach_hang_and_more"),
        ("users", "0003_nhanvien_chi_nhanh_ngan_hang_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tieu_de",
                    models.CharField(max_length=255, verbose_name="Tiêu đề đề xuất"),
                ),
                ("noi_dung", models.TextField(verbose_name="Nội dung")),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_duyet",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày duyệt"
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Chờ duyệt", "Chờ duyệt"),
                            ("Đã duyệt", "Đã duyệt"),
                            ("Từ chối", "Từ chối"),
                        ],
                        default="Chờ duyệt",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "phan_hoi",
                    models.TextField(
                        blank=True, verbose_name="Phản hồi của người duyệt"
                    ),
                ),
                (
                    "file_dinh_kem",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="proposal_attachments/",
                        verbose_name="File đính kèm",
                    ),
                ),
                (
                    "nguoi_de_xuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="de_xuat",
                        to="users.nhanvien",
                        verbose_name="Người đề xuất",
                    ),
                ),
                (
                    "nguoi_duyet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duyet_de_xuat",
                        to="users.nhanvien",
                        verbose_name="Người duyệt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("noi_dung", models.TextField(verbose_name="Nội dung chi tiết")),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                ("han_chot", models.DateTimeField(verbose_name="Hạn chót")),
                (
                    "uu_tien",
                    models.CharField(
                        choices=[
                            ("Thấp", "Thấp"),
                            ("Trung bình", "Trung bình"),
                            ("Cao", "Cao"),
                        ],
                        default="Trung bình",
                        max_length=20,
                        verbose_name="Độ ưu tiên",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đang tiến hành", "Đang tiến hành"),
                            ("Hoàn thành", "Hoàn thành"),
                            ("Đã hủy", "Đã hủy"),
                        ],
                        default="Mới",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "file_dinh_kem",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="task_attachments/",
                        verbose_name="File đính kèm",
                    ),
                ),
                (
                    "muc_tieu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.muctieu",
                        verbose_name="Liên quan đến mục tiêu",
                    ),
                ),
                (
                    "nguoi_giao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giao_viec",
                        to="users.nhanvien",
                        verbose_name="Người giao",
                    ),
                ),
                (
                    "nguoi_nhan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nhan_viec",
                        to="users.nhanvien",
                        verbose_name="Người nhận",
                    ),
                ),
            ],
        ),
    ]
