# Generated by Django 5.2.5 on 2025-08-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BangLuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ky_tinh_luong', models.DateField(verbose_name='Kỳ tính lương (chọn ngày đầu tháng)')),
                ('luong_co_ban', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lương cơ bản')),
                ('luong_tang_ca', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lương tăng ca')),
                ('phu_cap', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Phụ cấp')),
                ('khau_tru', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Khấu trừ')),
                ('thuc_lanh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Thực lãnh')),
            ],
            options={
                'verbose_name': 'Bảng lương',
                'verbose_name_plural': 'Bảng lương Nhân viên',
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ky_thanh_toan', models.DateField(verbose_name='Kỳ thanh toán (chọn ngày đầu tháng)')),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền')),
                ('trang_thai', models.CharField(default='Chưa thanh toán', max_length=50, verbose_name='Trạng thái')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_thanh_toan', models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Danh sách Hóa đơn',
            },
        ),
    ]
