# Generated by Django 5.2.5 on 2025-08-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("clients", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bangluong",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.nhanvien",
                verbose_name="Nhân viên",
            ),
        ),
        migrations.AddField(
            model_name="hoadon",
            name="hop_dong",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.hopdong",
                verbose_name="Hợp đồng",
            ),
        ),
    ]
