# Generated by Django 5.2.5 on 2025-08-30 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThongBao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("noi_dung", models.TextField(verbose_name="Nội dung")),
                (
                    "link_hanh_dong",
                    models.URLField(blank=True, verbose_name="Link hành động"),
                ),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("da_doc", models.BooleanField(default=False, verbose_name="Đã đọc")),
                (
                    "nguoi_nhan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ngay_tao"],
            },
        ),
    ]
